import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

// Components
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from "@/components/header/Navbar";
import Footer from "@/components/footer/Footer";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${outfit.className} antialiased`} >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main className="overflow-hidden m-auto mt-[65px] mb-30 md:mb-0 container min-h-[calc(100vh-65px-50px)] px-3 py-6 pb-15 md:py-15">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
